#!/usr/bin/env python2
# Copyright (C) 2011 Felix Kaiser
# License: revised BSD

import datetime
import re
import sys

EXPR = re.compile(r"(\d{4})-(\d{2})-(\d{2})")
FORMAT = "{0} ({1:%a})"


def main(text):
    sys.stdout.write(replace_text(text))
    sys.stdout.flush()

def replace_text(text):
    return EXPR.sub(replace_match, text)

def replace_match(match):
    date = datetime.date(*[int(match.group(i)) for i in (1,2,3)])
    return FORMAT.format(match.group(0), date)

if __name__ == '__main__':
    if len(sys.argv) == 1:
        main(sys.stdin.read())
    elif len(sys.argv) == 2 and sys.argv[1].lower() not in ("-h", "--help", "-?"):
        main(sys.argv[1])
    else:
        print >> sys.stderr, "adds the weekday to all yyyy-mm-dd strings in a text"
        print >> sys.stderr
        print >> sys.stderr, "usage:"
        print >> sys.stderr, "  {0} text".format(sys.argv[0])
        print >> sys.stderr, "  {0} < text".format(sys.argv[0])
        sys.exit(2)

